version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: product_like_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - "5432:5432"
