// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"database/sql"
	"time"
)

type Favorites struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	ProductID int64     `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Products struct {
	ID                int64           `json:"id"`
	ShopID            sql.NullInt64   `json:"shop_id"`
	Name              sql.NullString  `json:"name"`
	Description       sql.NullString  `json:"description"`
	ThumbnailUrl      string          `json:"thumbnail_url"`
	OriginPrice       int64           `json:"origin_price"`
	DiscountedPrice   int64           `json:"discounted_price"`
	DiscountedRate    sql.NullFloat64 `json:"discounted_rate"`
	Status            string          `json:"status"`
	InStock           bool            `json:"in_stock"`
	IsPreorder        bool            `json:"is_preorder"`
	IsPurchasable     bool            `json:"is_purchasable"`
	DeliveryCondition string          `json:"delivery_condition"`
	DeliveryDisplay   sql.NullString  `json:"delivery_display"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type Users struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Phone     sql.NullString `json:"phone"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt time.Time      `json:"deleted_at"`
}
